image:
  file: .gitpod.Dockerfile
# tasks:
#   - init: |
#       pip install -r requirements.txt
#       pip install -e .
vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - analytic-signal.preview-pdf
    - yzhang.markdown-all-in-one